# Generated by Django 3.0.7 on 2022-08-30 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20220830_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='designtaion',
            new_name='designation',
        ),
    ]
